//TODO
//Here the Operator has expressed the will to frontpay Bob peg-out.
//The Operator must do it and ZK prove it within 24 hours.
//If the Operator doesn't prove it, Bob can slash him getting the Operator's bond.
//Then Bob can create a new peg-out-request and restart the process.
//If the Operator proves the frontpayment within the time limit, he can send the Bob peg-out nft to peg-out-completed.ak
