//TODO
//Bob wants to peg-out (Cardano -> Bitcoin) without waiting the bridge time, getting his BTC on Bitcoin as soon as possible.
//Bob also doesn't need to worry about the safe time window when doing the peg-out.
//Bob locks his Cardano BTC in this validator with a premium (either ADA or other Native Tokens).
//Any one can become an Operator booking for 24h Bob's peg-out request and sending it to peg-out-in-progress.ak with a bond in ADA.
//Bob can cancel his peg-out request if no operator has booked it yet.
